(* ::Package:: *)

(* ::Input:: *)
(*TablRaw=Import["H:/mathematica/\:7a0b\:5e8f/\:7a0b\:5e8f/t3\:7684\:503c.xls"];*)
(*Tabl=TablRaw[[1]];*)
(*\[Delta]R=1.66;*)
(*Num=Length[Tabl];*)
(*Res={};*)
(*Quiet@Do[*)
(*\[Tau]=Tabl[[i]];*)
(**)
(*AppendTo[Res, {i,\[Tau],m=R/.FindRoot[-\[Tau]+0.5`/(1-R/(\[Delta]R +R)+Sin[(2 \[Pi] R)/(\[Delta]R+R)]/(2 \[Pi]))==0,{R,5}]}];*)
(*,{i,1,Num}];*)
(*Export["H:/mathematica/\:7a0b\:5e8f/\:7a0b\:5e8f/t3\:7684\:503c1.xls",Res];*)
